### get all data replies
GET http://localhost:8000/replies

### crete replies
POST http://localhost:8000/replies
Content-Type: application/json

{
  "text" : "ini adalah reply ke-tiga",
  "threadId": "66af12f5959c292639e35de3"
}

### update replies
PATCH http://localhost:8000/replies/66af155a959c292639e35df1
Content-Type: application/json

{
  "text" : "test update replies ke tiga",
  "threadId": "66af12f5959c292639e35de3"
}

### delete replies
DELETE http://localhost:8000/replies/66aea9b8fe379c7d792a20a0