### get all data replies
GET http://localhost:8000/replies

### crete replies
POST http://localhost:8000/replies
Content-Type: application/json

{
  "text" : "ini adalah reply terbaru",
  "threadId": "66b1af90368d09ef917215c5"
}

### update replies
PATCH http://localhost:8000/replies/66b0654d4485b072adba0a6a
Content-Type: application/json

{
  "text" : "test update replies terbaru 2",
  "threadId": "66af12f5959c292639e35de3"
}

### delete replies
DELETE http://localhost:8000/replies/66aea9b8fe379c7d792a20a0