### get all data thread
GET http://localhost:8000/threads

### crete thread
POST http://localhost:8000/threads
Content-Type: application/json

{
  "content" : "Thread Malam horror S3",
  "category" : "comedy",
  "authorId": "66adc7b0dd575e2aee2477e9"
}

### update thread
PATCH http://localhost:8000/threads/66af12f5959c292639e35de3
Content-Type: application/json

{
  "content" : "Thread Malam horror Update",
  "category" : "horror",
  "release": "2024-08-03",
  "authorId": "66adc7b0dd575e2aee2477e9"
}

### delete thread
DELETE http://localhost:8000/threads/66ae837474f4dab80c695e13