GET http://localhost:8000/users

### Create User
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Erine",
    "age": 18,
    "email": "erine@gmail.com",
    "password": "1234"
}

### Delete User
DELETE http://localhost:8000/users/66adc25535094921ca14cbce


### Update User
PATCH http://localhost:8000/users/66adc7b0dd575e2aee2477e9
Content-Type: application/json

{
  "name": "erine",
  "age" : 19,
  "email": "erine@gmail.com",
  "password": "123"
}