GET http://localhost:8000/users

### Create User
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "User4555",
    "age": 10,
    "email": "user4@gmail.com",
    "password": "1234"
}

### Delete User
DELETE http://localhost:8000/users/66af1119959c292639e35dda


### Update User
PATCH http://localhost:8000/users/66adc7b0dd575e2aee2477e9
Authorization: authkey123
Content-Type: application/json

{
  "name": "Erine",
  "age" : 18,
  "email": "cavallery@gmail.com",
  "password": "12345"
}